### ISSUE TITLE
Stuttering sprites

### ISSUE THREAD

**Issue by nullobject** [MiSTer-devel/Arcade-Cave_MiSTer#24]
Sometimes the sprites seem to stutter by a small amount as they are scrolling.

Unfortunately it doesn't happen all the time, so it's a bit of a pain to track down.

**Comment by xxserge85xx** [comment]
Yes, I've completed 2 runs and no problems whatsoever, but now i tried playing it and I'm noticing some stuttering in the scrolling.

Maybe I didn't see it before, but now is hard to "unsee it"

**Comment by IcarusFW** [comment]
Confirming that bullets and sprites stutter when the game is running at 57.5Hz - it is most noticeable on the stage 3 boss but occurs everywhere.
https://www.twitch.tv/videos/880435489?t=0h21m58s

**Comment by nullobject** [comment]
It's strange that it is only the sprites which stutter. The other tile layers are all smooth.

**Comment by nullobject** [comment]
This has been fixed :+1:
