### ISSUE TITLE
Image issue with analogue output for vertical orientation

### ISSUE THREAD

**Issue by 8PercentAndroid** [MiSTer-devel/Arcade-Cave_MiSTer#25]
When setting core to veritcal orientation mode the analogue image through CRT (component) is "quadrupled" see attached image
This issue persists whether the "flip screen" is set to on or off
HDMI output works fine
CRT output is fine when orientation is set to horizontal

Tested using _DoDonPachi (no warn).mra_ and _Arcade-Cave_20210113.rbf_

![20210113_101245](https://user-images.githubusercontent.com/58892466/104442752-6947e080-558d-11eb-9ca2-0c59cbed6cfb.jpg)

**Comment by nullobject** [comment]
Thanks for the report @8PercentAndroid, this is definitely a known issue :+1:

I think the people most annoyed by this are probably streamers who play on a CRT and record the HDMI. But it's definitely on my TODO list.

I think the solution is to use separate frame buffers for CRT and HDMI outputs, but that will require a little bit of extra work.

**Comment by 8PercentAndroid** [comment]
Ah sweet, just thought I'd flag it in case. please let me know if you need any further testing assistance

**Comment by mikey1964** [comment]
has this been fix iam not streaming just playing on my crt tv only it looks just like that picture . i also can not change to horizontal

**Comment by therourke** [comment]
Wondering if a fix for this is underway? Thanks

**Comment by mikey1964** [comment]
> Wondering if a fix for this is underway? Thanks

i fix this by deleting all the cave files that get the gaming running then had updater install new files

**Comment by nullobject** [comment]
This has been fixed in the latest beta :+1:
