### ISSUE TITLE
Missing Gamma correction

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Arcade-Cave_MiSTer#27]
In the core system option, there is no option for the gamma correction like other cores.

Thanks,

**Comment by nullobject** [comment]
This has been fixed :+1:

**Comment by wwark** [comment]
I checked the option gamma correction. 
It is added but the change value of the option doesn't seem to change gamma.
Thanks.

**Comment by nullobject** [comment]
@wwark Sure. It has been fixed, but I haven't released it yet :smile: 

It will be included in the next public relese.
