### ISSUE TITLE
Button C autofire work only with no warning mra 

### ISSUE THREAD

**Issue by Lmn-San** [MiSTer-devel/Arcade-Cave_MiSTer#29]
The button C that should be the autofire, is not working for the US, Japanese and Arrange version.
I don't know if this is related to the dipswitch missing?

**Comment by bibou42** [comment]
Dipswitch are not implemented yet in order to activate the C button.
The reason the No Warning mra can use the C button is because it apply a patch on the ROM.

**Comment by Lmn-San** [comment]
Thank you for the infos, I kind of suspected that.

**Comment by nullobject** [comment]
@Lmn-San All MRA files have been updated with the C-button and no-warn patches.

Closing this issue, I consider it fixed.
