### ISSUE TITLE
No audio in direct_video mode 

### ISSUE THREAD

**Issue by ghost** [MiSTer-devel/Arcade-Cave_MiSTer#32]
When using this core in direct_video mode with a Rankie HDMI to VGA adapter I get no audio. hdmi_audio_96k=1 or hdmi_audio_96k=0 doesn't make a difference and all the other cores I tested work fine in this setup. 

However, if I use the optical output of the Digital I/O Board v2.1 with an external DAC via SPDIF the audio works perfect.

**Comment by ercan1441** [comment]
+1 Same problem here.

**Comment by nullobject** [comment]
@ercan1441 Is this still an issue in the latest beta?

I am away from home and don't have my HDMI to VGA adapter with me to test this out.

**Comment by thehughhefner** [comment]
@ercan1441 Is this working now?

**Comment by ercan1441** [comment]
@nullobject @thehughhefner I no longer have this setup (HDMI->VGA adapter) and can therefore no longer test it,  sorry.

**Comment by nullobject** [comment]
@ercan1441 @thehughhefner No worries, I just dug out my HDMI to VGA adapter and hooked it up.

I get perfect video and audio out of my adapter (not sure which chip it uses) with `direct_video=1`, so this issue seems to be fixed :+1:
