### ISSUE TITLE
Core freezing on startup with MRA, RBF and ROM in correct locations

### ISSUE THREAD

**Issue by mfncl9991** [MiSTer-devel/Arcade-Cave_MiSTer#33]
Some of us over on classic gaming discord are seeing issues where DoDonPachi public release freezes with a black screen showing "Kbd mode: Joystick 1". 

I ran update_all to pull the files initially, and confirmed the MRAs and core RBF are where they should be (/media/fat/_Arcade/cores) , and I see the ROM zip in /media/fat/games/mame. 

/media/fat# ls -la "_Arcade" | grep DoDon
-rwxr-xr-x  1 root root     1121 Jan 13 22:07 DoDonPachi (Arrange).mra
-rwxr-xr-x  1 root root     1157 Jan 13 22:07 DoDonPachi (Japan).mra
-rwxr-xr-x  1 root root     1133 Jan 13 22:07 DoDonPachi.mra
-rwxr-xr-x  1 root root     1362 Jan 13 22:07 DoDonPachi (no warn).mra

/media/fat# ls -la "_Arcade/cores" | grep Cave
-rwxr-xr-x  1 root root 3888860 Jan 14 10:57 Arcade-Cave_20210113.rbf
-rwxr-xr-x  1 root root 3888860 Jan 13 22:07 Cave_20210113.rbf

/media/fat# ls -la "games/mame" | grep ddon
-rwxr-xr-x 1 root root  9734822 Sep  8 12:40 ddonpach.zip

/media/fat# md5sum games/mame/ddonpach.zip 
58a82638a2aa7e4e40b32bf365bff17d  games/mame/ddonpach.zip

Tried vsync_mode=0 but same behavior, suggesting this is not a display issue.
As a Patron I had beta 2 working in the past. I also ran jotego's 128MB module memory tester, and all passed OK, so I don't think its an SDRAM issue (CPS1.5 core working fine).

Update: also tried the DDR mode RBF, and the same freeze happens. This time instead of a black screen, I have a garbled frozen display (also with "Kbd mode: Joystick 1" status message frozen)

**Comment by mfncl9991** [comment]
Additional data point from CGD.. For users experiencing these symptoms, beta4 (Arcade-Cave_20210102.rbf) is working but beta5 onwards does not.

**Comment by Telzuim** [comment]
i have the same problem - got the files with the same script. Mister with XS-D 128MB SDRAM

**Comment by jlrh** [comment]
Same problem. Mister with 32MB SDRAM. Tested with SDRAM and DDR options. Tested with two different SD cards.

**Comment by alienator303** [comment]
same problem: black screen freeze with with "Kbd mode: Joystick 1" status message frozen, last beta worked, pulled the public release this morning and it crashes. (mister 128mb no blisterboard)

**Comment by nullobject** [comment]
@mfncl9991 Thanks for the detailed report. 

Obviously something funny is going on here, it doesn't sound like a SDRAM issue anymore.

I will dig into this today 🧐

**Comment by nullobject** [comment]
Ok, I'm closing this issue as it's a duplicate: https://github.com/MiSTer-devel/Arcade-Cave_MiSTer/issues/18

Let's move the discussion over there :+1:
