### ISSUE TITLE
Image scrolls vertically with analogue output

### ISSUE THREAD

**Issue by RWinton** [MiSTer-devel/Arcade-Cave_MiSTer#40]
Took a while for me to be (reasonably) certain that this issue stems from the core in some way and not my hardware.

First off, my setup is a MiSTer with an analog IO, outputting to a PVM-1351Q with a VGA -> BNC cable.

I have tried every combination of vsync_adjust settings, including setting upper and lower bounds for the refresh rate.  I have tried component output, RGB output, changing the V Hold settings on my monitor, internal/external sync settings, I've tried different cables even.  And under every circumstance the video in the DDP cores roll vertically.

Swapping between 57 and 60 on the MiSTer core:
https://youtu.be/cjl9Z2AnrC8

No other core, console or arcade, does this for me.  And I was going to chalk it up to my monitor just can't handle DDP's refresh rate, but later realized I could test my PCB on the monitor and see how that went.  So I re-pinned a SCART cable I'd had lying around to make an RGB cable (the pin for green is broken, so please ignore that) and here is the result.

DDP PCB:
https://youtu.be/re6CECqDkCA

Playing the PCB on this monitor works just fine, but using the DDP cores does not.

From a quick google it seems I'm not the only person.  User it290 on shmups forum has a similar model PVM (PVM-1342Q) and also can only get a scrolling image on his monitor.

**Comment by ihallin** [comment]
@RWinton thanks for confirming the PCB works. I'm it290 — I spoke to at least one other user on the classic gaming discord with a PVM-1342Q and they were experiencing the same issue.

**Comment by coderkind** [comment]
I experience this issue as well.![image](https://user-images.githubusercontent.com/940068/107866373-1bfaaf80-6e68-11eb-989d-92af54ae9690.jpeg)

**Comment by RWinton** [comment]
Tacking on here that the core also does not work on a PVM 1954Q, while the PCB does.

**Comment by nullobject** [comment]
Thanks for the updates.

I have some changes to the core which uses the exact video clock frequency as the original, which should hopefully fix this issue. Will make a release tonight.

For technical reasons, the video clock frequency was slightly off previously.

**Comment by nullobject** [comment]
I have pushed a new release uses a 7MHz video clock.

Could you please check whether this fixes your PVM sync issue?

**Comment by nullobject** [comment]
Assuming this was fixed, didn't hear back.
