### ISSUE TITLE
Scandoubler support (feature request)

### ISSUE THREAD

**Issue by mapfde** [MiSTer-devel/Arcade-Cave_MiSTer#41]
Hi,

the cave core currently does not use the scandoubler to output 31KHz analog signals. Please consider supporting it.

**Comment by joshuaryoung** [comment]
Would really love this

**Comment by nullobject** [comment]
Scandoubler works in the latest beta :+1:

**Comment by city41** [comment]
Scandoubler does not seem to do anything in the 220717 version. I have tested DonPachi and DoDonPachi, both with flip on and off. I am not rotating the screen. If I select a scandoubler option such as CRT 25%, nothing seems to happen.
