### ISSUE TITLE
Random black screens in 15kHz

### ISSUE THREAD

**Issue by Kasreyn** [MiSTer-devel/Arcade-Cave_MiSTer#42]
Hi,

In the latest core (Arcade-Cave_20210128.rbf) I see random short black screens that appear maybe one or two times. There can be no issue for several minutes before this happens again.
It only happens on VGA 15kHz, I have not seen it when the core is outputting 31kHz.

I made a short video where it can be seen:
https://clips.twitch.tv/PrettyCarefulVultureWutFace-5vV08HpJsX4-PecV

Thanks for all your work on this!

P.S.
The core's default output is 15kHz and ignore settings forced_scandoubler=1 / vga_scaler=1.
It does switch to 31kHz when "Scandoubler" menu option is something other than "None" (the same as in many other cores).

**Comment by nullobject** [comment]
Is this still and issue for you @Kasreyn?

**Comment by nullobject** [comment]
I haven't received any other reports, closing.
