### ISSUE TITLE
PS3 Controller Issue

### ISSUE THREAD

**Issue by Aspie66** [MiSTer-devel/Arcade-Cave_MiSTer#43]
Hi,
I was playing with the PS3 controller and the game kept freezing. I eventually found it was the controller that was causing the problem as the L3 button which is when you press in the left joystick was assigned to pause. Is this a default setting and could it be disabled?

I reassigned the pause to another button and the problem was fixed.

**Comment by thehughhefner** [comment]
It is always recommended to define buttons in the core. The reason is that the core will base the controller scheme based on what was defined in the mister main menu. In my opinion, this ticket can be closed

**Comment by nullobject** [comment]
Agreed.

@Aspie66 you need to play around with your default button settings.
