### ISSUE TITLE
Corrupted graphics

### ISSUE THREAD

**Issue by blisstik** [MiSTer-devel/Arcade-Cave_MiSTer#44]
Hello there,

Thank you for your contributions and work on this core.

I am just reporting that the new RBF on mister has severe graphics and audio corruption on the latest RBF and MRA file. The RFB from January works fine with the newer MRA, although it still asks to map that 3rd button.

**Comment by nullobject** [comment]
That sucks, sorry about that.

It is working fine for me. Would you mind posting a photo/video of what you are talking about?

**Comment by zakk4223** [comment]
This is what I'm seeing



https://user-images.githubusercontent.com/22642/113799729-9b4b8780-9723-11eb-8cd4-6f101440d099.mp4

**Comment by gnadenlos** [comment]
Same problem for me and Dangun Feveron doesn't work at all.

**Comment by itsTrifle** [comment]
Just a note to say I'm seeing the same issue - so I have rolled back to the last Patreon release.  Have not had any SDRAM issues on other cores thus far (128Mb)

**Comment by zakk4223** [comment]
I swapped to a 32MB SDRAM module and both Dangun and DDP work correctly now. My 128MB has never had issues with cps1.5/cps2, previous cave cores etc.

**Comment by BretYancy** [comment]
im in the same boat.
128mb RAM user, jotego cores run fine, but this latest update is causing graphical errors in DDP.

i see the above poster reported swapping to a 32mb module fixed the issue, but i dont have a 32 to test.
im super grateful for your work so far, and i hope this is an easy fix !

**Comment by BretYancy** [comment]
im in the same boat.
128mb RAM user, jotego cores run fine, but this latest update is causing graphical errors in DDP.

i see the above poster reported swapping to a 32mb module fixed the issue, but i dont have a 32 to test.
im super grateful for your work so far, and i hope this is an easy fix !

**Comment by IlIlIlIlIlIlIl** [comment]
Same issues here! Hopefully this is a easy fix. Setting the memory option to DDR3 seems to fix it, so it's definitely somehow SDRAM related

**Comment by ratherDashing** [comment]
+1 w/ 128.  Been playing almost daily since it went public and this is the first time ive seen corrupted graphics.  all other cores work perfect

**Comment by blisstik** [comment]
Likewise, 128 is causing it. Setting to 50 or 60 didn't fix the issue. I am running vsync_adjust = 0

**Comment by owlnonymous** [comment]
I  use a 128mb SDRAM and have the latest RBF and MRAs. I was getting corrupted graphics via HDMI but the analog output was fine. Setting the Refresh Rate to 57Hz, ROM Storage to DDR3, and adding the following like to the mister.ini fixed HDMI output for me.

[Arcade-Cave]
vsync_adjust=0

**Comment by bellwood420** [comment]
I don't encounter the graphical issue on 
- the latest RBF and MRAs
- 128MB SDRAM
- ROM Storage: SDRAM
- HDMI Output

Seems like timing issue?

**Comment by nullobject** [comment]
Thanks folks. I have been away from home (where most of my equipment is) for the past couple of months, but am heading home tomorrow.

I will have much more time to look into this issue (and keep working on the core) very shortly :smile:

**Comment by BretYancy** [comment]
thanks man!

for now, ive rolled back to the original 1/13/21 release, because i do play this game alot.
im not sure what the new update to the core improves, but i hope to enjoy the new release someday.

also, this may very well be an issue with the update-all script downloading an incorrect mame set rom and outdated rbf.
perhaps we can narrow down the culprits here and confirm **exact** files needed to run DDP and the rest of the 1st gen cave games.

if youre reading this, i dont need to explain how important these first cave titles are to the SHMUP community, especially DDP.
many thanks again, you rock dude!

**Comment by movisman** [comment]
Clearly some people are having issues, but everything seems to works fine for me. Most up to date and correct RBF/ROM, I can run at 57/60Mhz w/ SDRAM selected (coupled with any vsync_adjust setting), and I have no graphical issues with any combo. I wonder what might be going on to cause these issues for some users.

Curiously in the past with Jotego's early CPS1.5 releases, I had freezing issues with illegal instruction errors (a lot of others were having the same thing at the time), but this no stopped occurring after several updates from Jotego.

**Comment by springah** [comment]
Strange, works fine on DDR3, corrupt when using SD. Zero issues on any CPS cores.

**Comment by FatalTheory** [comment]
Hello similar to others I had a lot of issues when using 128mb sdram for the dodonpachi core. When I switched to DDR3 everything worked great.

**Comment by gnadenlos** [comment]
The 20 tests files from bellwood420s pull request worked for me. No more  graphical glitches and no crashes. I've tested all of them through level 1. Environment wasn't good enough to spot slight sound problems, so I can't really judge that part.
