### ISSUE TITLE
Service Button is missing from latest mra files

### ISSUE THREAD

**Issue by gnadenlos** [MiSTer-devel/Arcade-Cave_MiSTer#45]
Old:
`<buttons names="Shots/Laser,Spread/Laser Bomber,Full-Auto,Start,Coin,Pause,Service" default="A,B,X,R,L,Start" />`

New:
`<buttons names="Shots/Laser,Spread/Laser Bomber,Full-Auto,Start,Coin,Pause" default="A,B,X,R,L,Start" />`

Is there a reason for that? Service Menu worked fine for me and was useful to adjust difficulty.

**Comment by nullobject** [comment]
Fair enough.

I might move the service menu to the MiSTer options, as I was getting complaints from people who didn't like having to map the service button :D

**Comment by gnadenlos** [comment]
Would be fine for me too. Like CPS2 core I guess?

**Comment by nullobject** [comment]
> Would be fine for me too. Like CPS2 core I guess?

Yes, that's the plan :+1:

**Comment by nullobject** [comment]
This was rolled back, all MRAs now include the service menu.
