### ISSUE TITLE
SDRAM doesn't work, DDR3 does - Esp Ra.De.

### ISSUE THREAD

**Issue by dentnz** [MiSTer-devel/Arcade-Cave_MiSTer#49]
Switching the memory to DDR3 instead of the SDRAM option via the OSD sees the game booting up correctly.

**Comment by itsTrifle** [comment]
Same issue for me.  I also had SDRAM issues in the prev build until the issue#44 fixed that.

**Comment by gnadenlos** [comment]
Same problem here. 

Additional info:
I was also one of the users affected by the second to last Do Donpachi core problem.
Do Donpachi doesn't work for me at all with this new beta core (DDR3 and SDRAM).

**Comment by WinterCloak** [comment]
SDRAM appears to be broken for me as well. SDRAM worked fine in previous releases.

**Comment by nullobject** [comment]
Thanks for the bug report, will investigate this :+1:

**Comment by itsTrifle** [comment]
SDRAM now works for me in beta 20210516.  Thanks!

**Comment by nullobject** [comment]
> SDRAM now works for me in beta 20210516. Thanks!

This is good news.

I'm confident this issue has been fixed now. Closing...
