### ISSUE TITLE
Display issue during the attract mode

### ISSUE THREAD

**Issue by loloC2C** [MiSTer-devel/Arcade-Cave_MiSTer#5]
Beta version : Arcade-Cave_20200815.rbf

There's a display issue when transitioning from the title screen to the attract mode's level (cycling through the first 3 levels I think).
Here's a capture of the problem I posted on Youtube (unregistered): https://youtu.be/d4UyhjLC8vo

**Comment by nullobject** [comment]
Hi @loloC2C, thanks for capturing this issue back in August. I'm finally getting a chance to go back and fix these bugs.

What was this issue here? I can't quite tell from the video.

**Comment by loloC2C** [comment]
Hi @nullobject, the issue is what happens at 0:07 with the screen being filled with black before going white and then showing the (3rd) level. 

For reference here is another YT video done from the PCB : https://youtu.be/8GJ-8Tr6QQA with the same transition at 2:15. Notice that it's title screen -> white screen -> level and there's no black background at anytime.

**Comment by nullobject** [comment]
@loloC2C Ah, now I can see it. It's definitely still happening.

Thanks for pointing it out :eyes:

**Comment by huxmut** [comment]
Beta 3 exhibts same issue

**Comment by nullobject** [comment]
Yep, this is probably a bug in the layer priorities.

Interestingly the [score problem](https://github.com/nullobject/Arcade-Cave_MiSTer/issues/15) was caused by a sprite clipping issue. I was sure it was in the layers, but they render a lot of the text with sprites in this game :shrug:

**Comment by nullobject** [comment]
This is still occurring after fixing the sprite priority issues. There must still be a problem with the layers somewhere :thinking:

**Comment by nullobject** [comment]
I have figured out what is causing this issue: there is a special color in the palette which should be used to fill the frame buffer (I am only using black at the moment).

When the frame buffer is filled with this color, any changes to the palette (i.e. fade to white) will appear in the background.

I don't think I will fix this before release, but it is pretty high on my list now I know the cause of the issue :smile:

**Comment by nullobject** [comment]
This has been fixed :+1:
