### ISSUE TITLE
Strange loading behaviour on Puzzle Uo Poko

### ISSUE THREAD

**Issue by rascaluk** [MiSTer-devel/Arcade-Cave_MiSTer#50]
Getting some odd behaviour on Puzzle Uo Poko. First time it just black screened, now every time I load it I get a frozen DoDonPachi title screen.

In between it not working and this happening I tried the other three to see if they worked, all did.  I have cold rebooted and it's still there. Gonna power cycle now

OKay... After a power cycle I just get a screen of coloured noise now. It looks nice though! Like 100s and 1000s

**Comment by rascaluk** [comment]
Changed roms, works fine now!

**Comment by nullobject** [comment]
Glad you got it sorted :+1:
