### ISSUE TITLE
Coin up isn't working on Dangun Feveron

### ISSUE THREAD

**Issue by retroboobs** [MiSTer-devel/Arcade-Cave_MiSTer#52]
There appears to be a problem with Dangun Feveron core. It could be a symptom after using other Cave cores, although I haven't tracked this down.

With the recent two Beta's, upon first boot of Dangun, it is in FREE PLAY mode. On loading the game any subsequent time it in regular gameplay mode. When pressing the coin button I have assigned, I hear the noise for a credit, however it doesn't coin the game up at all. 

I am unable to get into the service menu of the game properly in the latest core (the screen just shakes).

I have tried clearing out config files and remapping with no luck either.

**Comment by retroboobs** [comment]
Strangest thing happened. Dangun Feveron is now working but Uo Poko isn't coining up at all.

This issue seems to stem from hopping between the cores. Please try it.

**Comment by nullobject** [comment]
Buttons are fixed for Uo Poko :+1:
