### ISSUE TITLE
Black Screen Through VGA. 

### ISSUE THREAD

**Issue by TigerRodriguez** [MiSTer-devel/Arcade-Cave_MiSTer#53]
I get a black screen through my vga out out. But the hdmi output does get a picture. I have reset all the settings for  the core and still nothing. I get a small flicker when the scan doubler is being changed from 75% to off.

**Comment by nullobject** [comment]
Is this still an issue @TigerRodriguez?

I have not had other reports of analog video being broken for other people.

**Comment by TigerRodriguez** [comment]
Yes it still happening to me.

**Comment by nullobject** [comment]
@TigerRodriguez What kind of CRT do you have?

The resolution for the Cave core is 320x240. Do you have problems with any other cores that run at higher resolutions (e.g. CPS2)?

**Comment by nullobject** [comment]
Closing this as I haven't heard back.
