### ISSUE TITLE
Dangun Feveron inaccuracy in bg animation?

### ISSUE THREAD

**Issue by felleg** [MiSTer-devel/Arcade-Cave_MiSTer#54]
https://youtu.be/Bz1D-uAF2Ow&t=30s

Looking in this video, the background in the select screen of Dangun Feveron has a "wave animation" which is not present in the current core (as of 20210529). Is this a known issue?

**Comment by nullobject** [comment]
This has been implemented in the latest beta :+1:

**Comment by felleg** [comment]
I am currently using the 20220506 beta core and the "wave animation" is not happening for me with `dfeveron.zip`.

**Comment by nullobject** [comment]
@felleg Glad to hear it!
