### ISSUE TITLE
Dodonpachi C button acting as A button?

### ISSUE THREAD

**Issue by felleg** [MiSTer-devel/Arcade-Cave_MiSTer#55]
I noticed in 20210521 version of the core, the C button in Dodonpachi acts as the A button. Holding C shoots the laser. 

Strangely, this bug is not present in Dangun Feveron or Esp Ra De, so the issue really seems to be with DDP.

**Comment by thehughhefner** [comment]
It works fine for me (v220409). This ticket can be closed

**Comment by felleg** [comment]
Indeed!
