### ISSUE TITLE
Image in wrong orientation with direct video on vertical 15 KHz monitor

### ISSUE THREAD

**Issue by janisc** [MiSTer-devel/Arcade-Cave_MiSTer#58]
This is probably a duplicate but I am reporting as I am not 100% sure. Anyway, on HDMI to my 1080p TV game works great. I just received HDMI to VGA adapter that I am using with direct video mode outputting to my 15KHz arcade cabinet. The games I have tested seem to work fine, but DoDonPachi is not vertical on the vertical monitor, but instead the image is sideways landscape orientation (90 degrees incorrect) and glitching (like multiple copies of the image). The menu shows that the orientation is "Vertical" and changing it is disabled (the entry is greyed out). I have tested both latest publicly available rbf and mras as well as latest beta.

**Comment by astnmrtn** [comment]
Do you have the scandoubler enabled etc in the ini file? I have exactly the issue you describe when I enable "horizontal". Why is your option greyed out?

**Comment by nullobject** [comment]
This has been fixed in the latest beta :+1:
