### ISSUE TITLE
Minor graphical issue: small gaps in boss life meter border in DoDonPachi

### ISSUE THREAD

**Issue by PaddyCo** [MiSTer-devel/Arcade-Cave_MiSTer#59]
The border for the boss life meter has these weird gaps not seen on real hardware or MAME

![Screenshot 2021-08-09 23-42-00](https://user-images.githubusercontent.com/1817423/128779533-95a1d42b-edc6-448f-a4cf-4bade8366b25.jpg)

**Comment by nullobject** [comment]
This has been fixed :+1:
