### ISSUE TITLE
Analyze CPU wait timing with PCB

### ISSUE THREAD

**Issue by loloC2C** [MiSTer-devel/Arcade-Cave_MiSTer#6]
Beta version : Arcade-Cave_20200815.rbf
The original hardware does slow-down at various occasions when the screen is filled with bullets / enemies however the core does not seem to replicate this behavior which affects gameplay as a result. (IIRC rwk was aware of that).

**Comment by huxmut** [comment]
Beta 3 definately has slowdowns.
@nullobject  can close this ??

**Comment by nullobject** [comment]
@huxmut Thanks. I might just rename this issue.

I still plan to do a proper CPU wait/timing analysis, but without a real DoDonPachi PCB it is difficult/impossible for me to measure things.

I *do* own a Dangun Feveron PCB, so perhaps I can do the timing analysis with this board instead and see if I can improve the accuracy of the core overall.

**Comment by nullobject** [comment]
Closing this issue.

I will do a timing analysis on the core with Dangun Feveron instead, as I own the PCB.
