### ISSUE TITLE
Minor graphical inaccuracy: background tile(?) with incorrect order on ship selection screen

### ISSUE THREAD

**Issue by PaddyCo** [MiSTer-devel/Arcade-Cave_MiSTer#60]
Probably the nit pickiest issue so far 😅 Noticed that there are a couple of pixels that incorrectly appear on-top of the laser/shot on the ship selection screen

MiSTer:
![Screenshot 2021-08-09 23-40-26](https://user-images.githubusercontent.com/1817423/128778673-c1cd455b-f9e9-4f09-9574-6febc1a9a120.png)

Capture from PCB (taken from [this video](https://youtu.be/HWDo_Xj9CUc?t=37)):
![Capture3](https://user-images.githubusercontent.com/1817423/128778993-9b36baf9-bd6b-41d6-9cbd-7edc2d81fdd8.PNG)

**Comment by nullobject** [comment]
Thanks for posting this. It looks related to the other issue with the health bar. I'll try to figure it out 🧐

**Comment by nullobject** [comment]
This has been fixed :+1:
