### ISSUE TITLE
Guwange coin error.

### ISSUE THREAD

**Issue by Akaifutari** [MiSTer-devel/Arcade-Cave_MiSTer#61]
Hi!

I have an issue with Guwange. When I insert the coin I can heard the "tooh!" sound but the screen never change to the tittle screen and the credit counter continues in 0 (Credit 0) instead of Credit 1. I can't start the game.

**Comment by Akaifutari** [comment]
Problem solved. Wrong rom version.

**Comment by MonokromFR** [comment]
Hi!
from which romset you pulled it from?
I have the same problem with Uo Poko
