### ISSUE TITLE
Background lags 1f, leading to desync with sprites during scroll

### ISSUE THREAD

**Issue by Mikejmoffitt** [MiSTer-devel/Arcade-Cave_MiSTer#62]
On the original hardware, tile data is fetched throughout a scanline, with a pipeline of only a few pixels in length. On the current implementation, backgrounds are drawn to a framebuffer, leading to them being displayed 1f later than they should. This ultimately results in sprites that scroll with the background being out of sync.

A possible fix might be to pre-fetch all needed tile data during hblank in a few short bursts, and fill a short line buffer in block RAM, so that BG fetches do not need to preempt the sprite framebuffer's access to memory.

**Comment by nullobject** [comment]
This has been corrected in the latest beta. Tilemaps are rendered while "chasing the beam", which allows for row offset and select effects to work properly.

Appreciate the report and suggestions :+1:
