### ISSUE TITLE
Puzzle Uo Poko Define Buttons Not Registering

### ISSUE THREAD

**Issue by dannahan** [MiSTer-devel/Arcade-Cave_MiSTer#63]
All the other games buttons register (FEVER SOS, DoDonPachi, Guwange, etc.) However, this didn't work when I tried to define buttons. I've reset and used different controllers.

**Comment by italiangrandma** [comment]
Just tried to play this one today and ran into the same issue.

**Comment by italiangrandma** [comment]
Ok, so someone on Discord shared the solution to this problem. To fix this, go to the bottom of the MRA and find this section:

`<buttons names="Start,Coin,Pause,Service" default="R,L,Start" />`

Change that to this:

`<buttons names="B1,B2,B3,Start,Coin,Pause,Service" default="A,B,X,R,L,Start" />`

Inputs now register as they should!

**Comment by PapiFed** [comment]
I can confirm the suggested fix works. Thanks @italiangrandma.

**Comment by dannahan** [comment]
Will this be on the latest build or can anyone push this branch up?

**Comment by nullobject** [comment]
Thanks for the fix, I will put this change in the next beta :+1:
