### ISSUE TITLE
Dodonpachi (Japan) core shows black screen, while the regular one works fine.

### ISSUE THREAD

**Issue by jamjyo** [MiSTer-devel/Arcade-Cave_MiSTer#64]
Dodonpachi (Japan) core shows black screen and doesn't work, while the regular Dodonpachi core works just fine.
Ran through memtest just in case, but I passed the test at 140mhz just fine.

Tried reinstalling everything, changing displays, changing vsyncadjust, but nothing seem to work so far.

Edit: Dodonpachi (Arracnge) also doesn't work.

**Comment by nullobject** [comment]
Hey @jamjyo, thanks for the report.

I will be working on the core over the xmas break so I will take a look at this issue.

**Comment by jamjyo** [comment]
Thank you for the fast response & hope you have a great xmas!

**Comment by aswgit** [comment]
@nullobject  I ran into this same issue recently and I believe the issue is due to update_all picking up the .mra from release directory, which have older versions of the .mra for Japan and Arrange.

**Comment by aswgit** [comment]
> Thanks for the suggestion. However, the linked version's auto-fure doesn't seem to work.
Try from the PR source.  I forgot I had patched the autofire locally.

**Comment by thehughhefner** [comment]
This ticket can be closed. I cannot reproduce this

**Comment by nullobject** [comment]
Great, thanks for the update :+1:
