### ISSUE TITLE
Add Akai Katana (akatana.zip) and Dodonpachi Saidaioujou (ddpsdoj.zip) following MAME removal?

### ISSUE THREAD

**Issue by ProjectLittleMan** [MiSTer-devel/Arcade-Cave_MiSTer#65]
Given [recent developments](https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=120280#Post120280
) with Exa-Arcadia and MAME regarding CAVE roms, does it make sense for MiSTerFPGA to take the lead in asserting the legal rights of FPGA true hardware replication users?

https://github.com/mamedev/mame/commit/54899379258a7266db8d5bc6cda8b48169e67503
```
31/12/2021:
   Akai Katana and Dodonpachi Saidaioujou removed at the request of the
   current rightholder, exA-Arcadia (legal@exa.ac).
```

The moderation team has established that "This doesn't hold any legal weight in the US at least", and that "There is no precedent in support of exa Arcadia forcing an emulators to stop supporting a rom". 

![FIMDug9XMAAPNFX](https://user-images.githubusercontent.com/93239553/147952855-0b98beb4-85bc-4a94-b51f-8edd21131340.jpeg)

With the many reasons folks "don't like mame", and adding this fiasco on top, MiSTerFPGA should give people one more reason to like hardware replication alternatives! Power to the #MiSTerFPGA!  

Can these ROMS be supported sooner than later, just to make a point?

**Comment by mrebersv** [comment]
Both Akai Katana and DDP SDOJ run on the CV1000 hardware, not the 68k that this project emulates.  I have no idea if nullobject plans on attempting the CV1000 hardware, nor do I know if the Mister can actually support that hardware, but it certainly wouldn't happen anytime soon unless someone else is already working on the CV1000 hardware elsewhere.

**Comment by birdybro** [comment]
This request can probably be closed as it's totally irrelevant to this core, unless @nullobject is planning on adding a Hitachi SH-3 implementation (impossible on the DE10-Nano most likely due to bandwidth), a recreation of the logic used in the Cyclone EP1C12 FPGA for the GPU, and a Yamaha YMZ770C-F implementation into this core.

The only purpose of this request is to troll me directly.

**Comment by nullobject** [comment]
@birdybro Exactly, this is not something I can action. And in any case, those games require a completely different architecture to this core.

Closing.
