### ISSUE TITLE
ESP Ra. De. graphics garbled when rotated on analog video

### ISSUE THREAD

**Issue by ruiner9** [MiSTer-devel/Arcade-Cave_MiSTer#68]
Using the analog I/O board in component mode into my CRT TV, the graphics on the TV get garbled when rotated 90 degrees, flipped or unflipped. I am using the latest core from the Update_all Script and this occurs with the English and Japanese rom variants. Images are attached.

![unnamed](https://user-images.githubusercontent.com/37946113/163020288-ce6bfd54-dd33-4bb8-af4b-8b286b3623d6.jpg)
![unnamed (1)](https://user-images.githubusercontent.com/37946113/163020298-45a91f3a-b4ef-4589-b3e0-6beefec8f8ce.jpg)
![unnamed (2)](https://user-images.githubusercontent.com/37946113/163020301-a3de2e97-7279-465e-b09f-f0a67c87962f.jpg)

**Comment by asturur** [comment]
is analog rotation supported? i don't think so? i can t rotate any games in analog mode. Could you rotate them in previous builds?

**Comment by nullobject** [comment]
@ruiner9 Thanks for reporting this.

@asturur No, HDMI rotation always messed up the analog output due to the way the GPU worked internally.

The GPU rewrite I'm currently doing should fix this (and other) issues.

**Comment by asturur** [comment]
I m probably misunderstanding the issue.
I don't expect analog video to be rotated on request.
Is that correct?

**Comment by ruiner9** [comment]
Other arcade cores rotate analog video without issue, so there is precedent for this issue being resolved.

**Comment by asturur** [comment]
i was unaware that some does! i always thought it was an hdmi feature at the cost of a frame buffer or a possibility activating the vga scaler.

How that would work? what would be the final resolution of the analog out? could it go out of the 15khz range?
this thing now makes me curious.

**Comment by nullobject** [comment]
This has been fixed in the latest beta. It will go public soon.

Thanks for the comments everyone :heart:
