### ISSUE TITLE
Mister nightlies not building

### ISSUE THREAD

**Issue by asturur** [MiSTer-devel/Arcade-Cave_MiSTer#70]
While i know that is not necessary and that the code could be utterly broken, is still nice to try random builds sometimes.
Do you have any idea why the unstable nightlies repo isn't able to build your repo?

https://github.com/MiSTer-unstable-nightlies?q=&type=all&language=&sort=

If that is a choice is fine.
If is a technical issue, do you think is worth solving it?

**Comment by asturur** [comment]
ohhh i posted too soon.
It seems there is a documented procedure:
https://github.com/MiSTer-unstable-nightlies/Build-Automation_MiSTer#readme

**Comment by thehughhefner** [comment]
This ticket can be closed. Mister nightlies is not recommended since it builds a core based on code that might not be 100% working.

**Comment by asturur** [comment]
That is 100% what nightlies are. snapshots of a repository and exist for a reason.
Then @nullobject may want to have them or not or maybe is build process is slightly different and they can't work.
Nightlies are shortcuts for people that would pull down the source code and build it on their own, just for the sake of checking what is going on when they are bored, but without going in the build process. Is not a place where to find the latest version.

So is not recommended, but not recommended from who? Who is the recommender here?
