### ISSUE TITLE
Puzzle Uo Poko - Controller inputs not working

### ISSUE THREAD

**Issue by stephenpope** [MiSTer-devel/Arcade-Cave_MiSTer#71]
Using beta core: `Cave_20220506`

Cant register inputs, even after remapping the inputs to my joystick none of the inputs are working/registered (ie `coin` / `start`)

Extra details: Brook Pi Zero Fighting board using X-Input (PC)

Let me know if you need any more info :)

**Comment by nullobject** [comment]
@stephenpope Thanks for the report. I thought I fixed this issue, but just checked on my MiSTer and have the same problem :disappointed: 

Will fix and release in the next beta :+1:

**Comment by nullobject** [comment]
This has been fixed.
