### ISSUE TITLE
Raindrop effect on Dangun Feveron? (20220506 beta)

### ISSUE THREAD

**Issue by felleg** [MiSTer-devel/Arcade-Cave_MiSTer#73]
https://www.youtube.com/watch?v=omOyRJi5AGo&feature=youtu.be

Dangun Feveron exhibits a strange "popping/raindrop" effect in the 20220506 beta release.

**Comment by thehughhefner** [comment]
Is this only occurring when pausing the game or during gameplay as well?

**Comment by felleg** [comment]
Both, as soon as the core starts running.

**Comment by thehughhefner** [comment]
Great thank you for the quick reply.

**Comment by nullobject** [comment]
@felleg Thanks for the report.

I have seen this too, but for me it happens rarely. Does it always occur when you run the core?

**Comment by felleg** [comment]
2/2 boots so far.

**Comment by nullobject** [comment]
@felleg No worries.

Investigating this is on my list of stuff to do, but it is more difficult for me to track down because it doesn't occur often.

**Comment by nullobject** [comment]
This has been fixed, please check the latest beta :+1:
