### ISSUE TITLE
Random stutter spikes on Guwange (20220506 beta)

### ISSUE THREAD

**Issue by felleg** [MiSTer-devel/Arcade-Cave_MiSTer#74]
https://www.youtube.com/shorts/HRAx8B5QnoQ

I don't know if it's easy to notice in video, but when the screen is very busy in Guwange, sometimes we get strange stutter effects that I believe were not present on the original PCB. It's hard to predict when it will happen, but the level 1 boss in particular makes it happen often.

**Comment by nullobject** [comment]
Yep. I need to investigate what is causing the performance issues :thinking:

**Comment by nullobject** [comment]
This should be improved in the next beta.

It would be great for someone with a PCB to confirm whether the slowdowns look correct. From watching videos of the original PCB, I can see it does have huge slowdowns when things get busy. But the stuttering was a bug, thanks for reporting it :+1:

**Comment by felleg** [comment]
I tried the 20220520 beta and the issue seems resolved. Feel free to close this issue on my behalf. Thanks Josh!

**Comment by nullobject** [comment]
@felleg Excellent, glad to hear it.
