### ISSUE TITLE
Dangun Feveron - Minor graphical issue

### ISSUE THREAD

**Issue by stephenpope** [MiSTer-devel/Arcade-Cave_MiSTer#75]
Beta: Cave_20220512

(Wasn't sure whether to report this or not as its so tiny, but i checked MAME and some other cab videos and couldn't see it but please close if its too minor)

The first boss ship seems to have a pixel or 2 gap down the centre of it. I don't think its there permanently but its certainly noticeable. Not sure if its to do with the effect when you beat it and it evaporates into pixels.

![image](https://user-images.githubusercontent.com/689099/168161756-cdf8318a-31b0-422d-aac2-5f65ec225021.jpeg)

**Comment by nullobject** [comment]
@stephenpope Thanks, I will check this on my PCB this weekend.

**Comment by stephenpope** [comment]
Fourth level boss has the same issue.. 

![image](https://user-images.githubusercontent.com/689099/168665538-e22aabba-fa8a-4a7a-b84a-5e17672659f3.jpeg)

Here you can see its in the centre of each sprite (even when offset)

![image](https://user-images.githubusercontent.com/689099/168665686-f12f66f4-28ff-4166-aff5-03c3df0b8566.jpeg)

Also there is corruption when you complete the game..

![image](https://user-images.githubusercontent.com/689099/168665921-64821f58-fc78-4771-b63c-55b11eac7e26.jpeg)

**Comment by nullobject** [comment]
Thanks for the screenshots, I have fixed the sprite issue.

What a shame about the tilemap corruption at the end of the game, that is going to be a PITA to test :stuck_out_tongue_winking_eye:

**Comment by stephenpope** [comment]
Thanks, thats great news that you fixed it. Just build in a level select :) 20 minutes in and out  .. no problem ! :trollface:

**Comment by thehughhefner** [comment]
@stephenpope Does the latest release fix this issue?

**Comment by stephenpope** [comment]
Latest release fixes the pixel-line issue. I have not checked the end-of-game corruption.

**Comment by nullobject** [comment]
I played through with release 20220530 and this is what I see on the credits:

![Screenshot from 2022-05-31 11-57-22](https://user-images.githubusercontent.com/3614/171082758-260d4d45-053c-423e-86e5-ce05047e99c5.png)

Obviously, there are slight variations for the end page (maybe based on which ship you play?). But I don't see any corrupt graphics.

> I just played through the game and the end credits still has issues, however, they look different than what @stephenpope shared.

@thehughhefner Was this on release 20220530?

**Comment by thehughhefner** [comment]
Ok, I didn't know that there were variations on the end credits based on the ship (or something like that).
I have a faint memory of how the end credits looked like when I played, but the image appeared multiple times (in the video it only appears one time).

**Comment by nullobject** [comment]
I'm closing this. If I find scrambled tiles in the credits again I will reopen it, but so far so good.
