### ISSUE TITLE
ESP Ra.De. Free Play Patch

### ISSUE THREAD

**Issue by dannahan** [MiSTer-devel/Arcade-Cave_MiSTer#77]
If possible, would you include the free play patch as an alternative rbf?

https://shmups.system11.org/viewtopic.php?f=1&t=61617

Thanks again for all your hard work!

**Comment by thehughhefner** [comment]
This is a rom hack which means that an alternate mra is needed here. Maybe atrac17 can include it in their arcade offset repo

**Comment by nullobject** [comment]
Thanks, but this is low priority for me.

If someone else from the community would like to contribute a MRA, I would be happy to merge it.

**Comment by terminator2k2** [comment]
ive just made the mra files for international and japan ESP Ra.De Freeplay mods

[ESP Ra.De. FreePlay MRA.zip](https://github.com/MiSTer-devel/Arcade-Cave_MiSTer/files/8769966/ESP.Ra.De.FreePlay.MRA.zip)

**Comment by nullobject** [comment]
![](https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)

**Comment by nullobject** [comment]
@dannahan Closing this, @terminator2k2 is submitting a PR to the alternatives repo for the freeplay ROM hack.
