### ISSUE TITLE
PCBs Test Menu Settings didn't save ?

### ISSUE THREAD

**Issue by wolfsoftgmbh** [MiSTer-devel/Arcade-Cave_MiSTer#78]
I tried to go into the TEST Menu of ddonpach with holding service Button and Start and changed some parameters like difficulty, invert screen (needed here for my CRT standing tate Mode) and saved it via holding Service Button and Start again. 
I saved the core settings too. 
But after a game Reset all settings are default

Thanks for this great core

**Comment by thehughhefner** [comment]
Maybe someone else can chime in but I think NVRAM save support is needed here similar to CPS2.

**Comment by nullobject** [comment]
> Maybe someone else can chime in but I think NVRAM save support is needed here similar to CPS2.

Correct, I need to implement the NVRAM uploading.

**Comment by wolfsoftgmbh** [comment]
Hope you will find the time to add NVRAM support :-)
Thanks

**Comment by nullobject** [comment]
This has been fixed and will be included in the next release.

**Comment by nullobject** [comment]
This has been fixed in the latest release (20220530).
