### ISSUE TITLE
Flip screen not working with latest release on analog i/o

### ISSUE THREAD

**Issue by skankcore** [MiSTer-devel/Arcade-Cave_MiSTer#81]
I can't get the core to flip screen with the analog i/o after updating to the latest release. The toggle does nothing when activated and saving settings and resetting the core after toggling Flip Screen also does nothing.

**Comment by nullobject** [comment]
I had to drop this with the new graphics pipeline, but I'll see if I can get the analog flipping working again.

To flip analog, I need to double-buffer each line of the 3 tilemap layers. So that's an extra 320x6x16BPP (i.e. 3840 bytes) of BRAM. Should be doable.

**Comment by Lyriell** [comment]
Just wanted to say thank you for looking into this.   It makes my life easier not to have to unbolt and spin my monitor, or have to swap the yolk wires <3

**Comment by nullobject** [comment]
This has been fixed and will be included in the next release.

**Comment by ralphmoth** [comment]
Any idea when the next release will be please?  I have the same issue.

**Comment by nullobject** [comment]
> Any idea when the next release will be please? I have the same issue.

@ralphmoth Yes, today :smile:

**Comment by nullobject** [comment]
This has been fixed in the latest release (20220530).
