### ISSUE TITLE
20220520 Guwange hiccups in scrolling

### ISSUE THREAD

**Issue by felleg** [MiSTer-devel/Arcade-Cave_MiSTer#83]
Guwange seems do have hiccups at a rate of ~2Hz throughout the game. It does not really affect gameplay, but it  is very noticeable on the high scores screen. This happened 2/2 boots of the core.

![image](https://user-images.githubusercontent.com/7781739/169537221-9ece4455-111e-46fe-84d1-35673d7a391e.png)

**Comment by nullobject** [comment]
Thanks for reporting this.

What `vsync_adjust` setting do you have in your `mister.ini` file?

I would recommend using `vsync_adjust=1` for the smoothest performance at the original refresh rate.

If you aren't using this, please try it and report back.

**Comment by felleg** [comment]
Good catch! I have vsync at `Match display frequency` for whatever reason. Setting it to `Match core frequency` fixed the issue.

**Comment by nullobject** [comment]
Yay :tada:

**Comment by nullobject** [comment]
> Good catch! I have vsync at Match display frequency for whatever reason. Setting it to Match core frequency fixed the issue.

@felleg Remember, you can change this in your config on a per-core basis if you need to. Matching the core frequncy will always be the best option, as long as your display can handle the refresh rate :+1:
