### ISSUE TITLE
XML Parse error for DoDonPachi Trainer?

### ISSUE THREAD

**Issue by felleg** [MiSTer-devel/Arcade-Cave_MiSTer#84]
When trying to launch `DoDonPachi Trainer (Japan).mra`, there seems to be an XML issue preventing the game from launching.

![image](https://user-images.githubusercontent.com/7781739/169538888-cde1849a-1887-4fa4-9f64-3ec792dd2ca4.png)

**Comment by nullobject** [comment]
Thanks for checking this, I'm a peanut 🥜

I added a last-minute comment the the MRA file that broke things. Will repost this file on patreon.

**Comment by nullobject** [comment]
This has been fixed, I reuploaded the ZIP file on the patreon post.
