### ISSUE TITLE
ESP Ra.De. MRA Sprite Layer Issue

### ISSUE THREAD

**Issue by owlnonymous** [MiSTer-devel/Arcade-Cave_MiSTer#85]
MRA has sprite layering issue
https://github.com/MiSTer-devel/Arcade-Cave_MiSTer/blob/main/releases/ESP%20Ra.De..mra

**Comment by nullobject** [comment]
Hey @owlnonymous, sorry what is the issue with ESP Ra.De.?

**Comment by owlnonymous** [comment]
The sprites are below the background layer, and not appearing. I can provide video proof if needed.

**Comment by nullobject** [comment]
@owlnonymous That is odd...I wonder what the issue is because both the Japan and International versions look correct to me :thinking: 

When you have a minute, could you please attach a screenshot?

Thanks.

**Comment by thehughhefner** [comment]
I just checked and it looks fine for me. Maybe the layers are turned off in the debug menu?

**Comment by nullobject** [comment]
@thehughhefner Ah good point, there were a couple of changes to the menu options.

@owlnonymous Does this fix it for you?

**Comment by nullobject** [comment]
Closing this. Haven't heard back, but I am assuming the debug options were the issue.

**Comment by owlnonymous** [comment]
I'm sorry. Just seeing these responses. Sprite and system Framebuffers were turned off by default. I turned them on and everything is good to go.
