### ISSUE TITLE
Guwange Graphical Garbage

### ISSUE THREAD

**Issue by Missingno255** [MiSTer-devel/Arcade-Cave_MiSTer#86]
In Guwange, in the 4th stage when the worm creature (demon? I'm not too familiar with medieval Japan) explodes out of one of the buildings, there's green graphical garbage that are supposed to be brown explosion sprites. A few of the explosions do appear correctly.
The issue is always reproduceable. I don't know if the same problem appears in the stages after stage 4.

**Comment by nullobject** [comment]
Thanks for the report @Missingno255.

This is a known issue, and very annoying to track down since I have to play the game to stage 4 before I can try to debug it 😅

**Comment by nullobject** [comment]
![Uploading Guwange Sprite Bug 3.png…]()

**Comment by nullobject** [comment]
![Guwange Sprite Bug 3](https://user-images.githubusercontent.com/3614/169750454-5e5ef211-a854-4c93-b3ff-9b24965bad82.png)

**Comment by thehughhefner** [comment]
@Missingno255 Does the latest release fix this issue?

**Comment by nullobject** [comment]
@thehughhefner It hasn't been fixed yet. Coming soon 😀

**Comment by Missingno255** [comment]
> The latest release (20220530) appears to have resolved this issue.
> 
> I have played through and do not see the worm sprite glitch ✅
Yep I don't see it either! I'll let you know if any more issues come up!
