### ISSUE TITLE
Black screen all Cave cores

### ISSUE THREAD

**Issue by Aquas77** [MiSTer-devel/Arcade-Cave_MiSTer#88]
Ran update_all today 5/29/22 and the Cave core ceased to boot up for all games. Ah yes, I tried the 5/29 build for the Cave for as well as 5/22 build and same result.
It runs "Assembling rom #0" prompt, then quickly goes to a black screen, with the OSD immediately accessable.

Tried a variety of things to attempt to fix it. Re-downloaded roms, checked for any pre-existing cores. Deleted cfg files. Re-downloaded MRAs. I'm on 32mb ram if that's a needed detail.

**Comment by nullobject** [comment]
Hey @Aquas77, unfortunately the requirements for the core have changed.

You need at least 64MB of SDRAM to run it now, because some of the games on this core (e.g. ESP Ra.De. and Guwange) require more memory.

I will try to see if I can squeeze things back down to 32MB, but it may not be possible.

**Comment by Aquas77** [comment]
OH, Darn, I was wondering about that but I didn't see the info around! Maybe I didn't read close enough. Shoot! Okay, thanks. That would explain it.

**Comment by nullobject** [comment]
@Aquas77 All good, I shuffled things around and I think I have it working with 32MB SDRAM now.

Will be fixed in the next release (i.e. today).

**Comment by Toryalai1** [comment]
FYI, I am running MiSTer with dual ram set up (128mb on the main port and 32 mb on the secondary port), and I faced the same issue as Aquas

**Comment by nullobject** [comment]
@Aquas77 @Toryalai1 

I have pushed a new release which adds 32MB SDRAM support. Please take if for a spin and let me know whether this fixes the issue for you.

**Comment by Toryalai1** [comment]
With the new release, this now works for me.

Just for the record, as I mentioned yesterday, I have a dual ram set up (128 mb on the main port and 32 mb on the secondary port). Updating the mister main to the latest release, the core didn't work for some reason (even though this core wasn't updated until today).

**Comment by nullobject** [comment]
> With the new release, this now works for me.

Glad to hear it.

The core is also running reliably for me on a MiSTer with 32MB SDRAM ✅
