### ISSUE TITLE
Dangun Feveron

### ISSUE THREAD

**Issue by kaloun34** [MiSTer-devel/Arcade-Cave_MiSTer#89]
Hello,
With the version of Core and MRAs of 20220530, I can no longer put credit for "Dangun Feveron" and "Guwange"

**Comment by nullobject** [comment]
Please double-check your button mappings. Let me know if it fixes things?

Kind regards

Josh
________________________________
From: kaloun34 ***@***.***>
Sent: Monday, May 30, 2022 5:50:44 PM
To: MiSTer-devel/Arcade-Cave_MiSTer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MiSTer-devel/Arcade-Cave_MiSTer] Dangun Feveron (Issue #89)


Hello,
With the version of Core and MRAs of 20220530, I can no longer put credit for "Dangun Feveron"

**Comment by nullobject** [comment]
Excellent 😘👌

Kind regards

Josh
________________________________
