### ISSUE TITLE
guwange (special) Service Mode not accessable

### ISSUE THREAD

**Issue by wolfsoftgmbh** [MiSTer-devel/Arcade-Cave_MiSTer#90]
it didn't enter the service Mode when Service Mode in Mister Menu is pressed

thanks for invert screen function :-) and go on!

**Comment by nullobject** [comment]
> it didn't enter the service Mode when Service Mode in Mister Menu is pressed

@wolfsoftgmbh That's a shame, for which game?

**Comment by nullobject** [comment]
> it didn't enter the service Mode when Service Mode in Mister Menu is pressed

That's a shame, I didn't notice this before but it is definitely an issue. Thanks for reporting it.

**Comment by nullobject** [comment]
@wolfsoftgmbh It seems that Guwange (Special) uses a different button for service mode than everything else.

I made a tweak to the MRA file which should fix the issue. Let me know if this works for you.

**Comment by wolfsoftgmbh** [comment]
thanks for the lightspeed fix
GO ON!

**Comment by thehughhefner** [comment]
This ticket can be closed :)
