### ISSUE TITLE
Flip option doesn't works anymore on CRT 15 Khz monitor?

### ISSUE THREAD

**Issue by lroby74** [MiSTer-devel/Arcade-Cave_MiSTer#91]
Hello,
I've noticed that game now has image upside down on (rotated) CRT 15 Khz monitor (connected via Scart from VGA output) and 
"flip screen" option isn't working anymore (it works only on HDMI output).
Same thing for other Cave games and on Mister of my friend with same setup.

**Comment by nullobject** [comment]
Hi @lroby74

As you said, the "flip screen" option in the MiSTer menu is for HDMI output only. Analog flipping (aka invert screen) is now controlled through the in-game service menu (much like for a real arcade PCB).

You can adjust this in two ways:

1. The easiest thing to do is reset all settings for the game and start fresh. Select "Reset settings" in the MiSTer system menu and reload the core. This will start with the default settings which have the "normal" flipping mode enabled.
2. Or, select "Service mode" from the MiSTer menu. Then go into the in-game configuration scren and change "invert screen" to "normal screen". To permanently save the settings you have to exit the service menu (by selecting "Service mode" again), and then select "Save settings" in the MiSTer system menu.

Let me know if it fixes the issue for you.

**Comment by lroby74** [comment]
Hello again,
I've found invert screen into Service menù and it worked!
Thank you very much

**Comment by nullobject** [comment]
Yay :tada:
