### ISSUE TITLE
Guwange visual glitch on stage 4

### ISSUE THREAD

**Issue by felleg** [MiSTer-devel/Arcade-Cave_MiSTer#92]
In stage 4, there is a snake-creature that pops out of a house ([time stamped video from MAME](https://youtu.be/sypc871SLCo?t=55), not my own, my recording failed unfortunately...). The explosion in the 20220530 core has big green squares instead of actual explosion graphics.

![image](https://user-images.githubusercontent.com/7781739/173097442-d1848a79-6797-49dc-9e8e-30d7deef8cbf.png)
(screenshot from YouTube video for reference, does NOT show the glitch)

**Comment by thehughhefner** [comment]
The issue that you mention is related to this issue (which was closed): https://github.com/MiSTer-devel/Arcade-Cave_MiSTer/issues/86
Does the glitch appear consistently or is it random? @nullobject confirmed it being fixed in the 20220530 version of the core.

**Comment by thehughhefner** [comment]
Ok, so if you were using 20220506 and saw the glitch then there is a regression

**Comment by nullobject** [comment]
I am away for work for the week, but when I get back I will play through Guwange and double-check this.

**Comment by fiermanb** [comment]
Just checked: the glitch is not present anymore in the 20220619 release.

**Comment by felleg** [comment]
Thank you!
