### ISSUE TITLE
DonPachi audio bug

### ISSUE THREAD

**Issue by Missingno255** [MiSTer-devel/Arcade-Cave_MiSTer#94]
There appears to be some sort of balancing issue with the music where it's really quiet most of the time and gets loud randomly, and that back to being really quiet. Always reproduceable.

**Comment by nullobject** [comment]
Hey thanks for taking the time to report this.

Are you sure the volume changes aren't present in the original PCB? Unfortunately I don't own one, but from what I can see/hear in videos of the original arcade hardware the sound changes in volume too.

For example:

https://www.youtube.com/watch?v=T700t-S_IWY

**Comment by Missingno255** [comment]
> Hey thanks for taking the time to report this.
> 
> Are you sure the volume changes aren't present in the original PCB? Unfortunately I don't own one, but from what I can see/hear in videos of the original arcade hardware the sound changes in volume too.
> 
> For example:
> 
> https://www.youtube.com/watch?v=T700t-S_IWY
Hey no problem! Bugs need to die and accuracy is what counts, right?
I don't know if that was a problem on the original PCB or not, as I never played it on hardware before, some I'm not exactly sure. I did watch the video you linked, and it does sound similar. Hopefully someone else can confirm this?

**Comment by thehughhefner** [comment]
Here is another source: https://www.youtube.com/watch?v=lQUplGn1y7Q
I think it is supposed to sound like that
